---
# tasks file for bharath.rsyslog
- name: Install prerequisites
  yum:
    name:
      - liblogging
      - libgt
      - libestr
      - json-c
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Update Rsyslog from bharath yum-repository
  yum: pkg="rsyslog-{{rsyslog_version}}" state=present enablerepo=bharath
  when: ansible_distribution_major_version|int < 7

- name: write new Rsyslog config file from template
  template: >
    src=rsyslog.conf.EL{{ansible_distribution_major_version|int}}.j2
    dest=/etc/rsyslog.conf
    mode=644
  notify: restart rsyslog

- name: remove old remote.conf
  file: name=/etc/rsyslog.d/remote.conf state=absent

- name: write Rsyslog configuration file
  template: >   
    src=00-remote.conf.j2
    dest=/etc/rsyslog.d/00-remote.conf
    mode=644
  notify: restart rsyslog
